### ISSUE TITLE
Add support for outputting desired start/end time in Events

### ISSUE THREAD

**Issue by tedpelas** [C4ptainCrunch/ics.py#146] opened 2018-10-05 15:03 UTC
When creating a new calendar in version 0.4 the calendar output does not represent the desired times, only the dates are accurate:

```python
>>> from ics import Calendar, Event
>>> c = Calendar()
>>> e = Event()
>>> e.name  = "Something Something"
>>> e.begin = '20181004 08:00:00'
>>> e.end   = '20181011 08:00:00'
>>> c.events.add(e)
>>> c.events
{<Event 'Something Something' begin:2018-10-04T00:00:00+00:00 end:2018-10-11T00:00:00+00:00>}
```

08:00:00 is replaced by 00:00:00 for both begin and end unfortunately.

**Comment by C4ptainCrunch** [comment] 2018-10-22 22:44
Oh, that's really unfortunate (and quite a big problem).
I guess the source of the bug is in the date parsing of arrow.
Could you try by formatting your datetime string differently ? (With something like `2018-10-04T08:00:10` for example)

**Comment by C4ptainCrunch** [comment] 2018-10-28 22:48
I can't reproduce the issue after the changes to arrow 0.10 on master so i close the issue but if you still have the bug on master and you can give a minimal example, i'll be happy to open it again :)

**Closed by C4ptainCrunch** 2018-10-28 22:48 UTC
Labels: bug
