### ISSUE TITLE
setting a specific timezone

### ISSUE THREAD

**Issue by skandix** [C4ptainCrunch/ics.py#119] opened 2018-04-18 19:10 UTC
i would like to pass in that the calendar uses a specific timezone, how would i do so.. as I can't see any examples on how to do it properyl in the documentation.

i.e If i was to pass in Europe/Oslo as the timezone it would use .

**Comment by C4ptainCrunch** [comment] 2019-06-11 21:30
We don't have support for that at the moment, sorry :/ This is a duplicate of #129, i'm closing.

**Closed by C4ptainCrunch** 2019-06-11 21:30 UTC
Labels: Question
