### ISSUE TITLE
Update Arrow support to 0.11

### ISSUE THREAD

**Issue by jekku0966** [C4ptainCrunch/ics.py#101] opened 2017-08-16 17:02 UTC
Currently used Arrow version does not support `.shift()` which is easer to get tomorrows date.

Any workaround available?

**Comment by C4ptainCrunch** [comment] 2018-01-29 15:08
The Arrow API changed quite a lot, the update won't be trivial unfortunately :/
Bumping the arrow version is in my todo list but not at the very top (recurring events first). I might also choose to drop arrow and use the stdlib + some custom parsing functions, we'll see...

**Comment by C4ptainCrunch** [comment] 2018-01-29 15:09
Duplicate of #77

**Closed by C4ptainCrunch** 2018-01-29 15:09 UTC
Labels: feature request
