### ISSUE TITLE
UTF-8 Support

### ISSUE THREAD

**Issue by MerlinElMago** [C4ptainCrunch/ics.py#154] opened 2018-12-09 12:33 UTC
I am having tons of problems with UTF-8 formatted strings. 
As my native language is spanish, we have all kinds of letters like `áéíóú` or `ñ` in names, words and appointments. 
I'm on Mac, and this throws an error no matter what I try:
`Event( name="Name", begin=myTime1, end=myTime2, duration=None, uid=None, description="Función"
			+myFunction, url="https://....html", transparent=False, alarms=None, categories=None, status=None )`

Best regards
Merlin

**Comment by C4ptainCrunch** [comment] 2018-12-10 08:10
Hi @MerlinElMago !

Could you give a full example of a code that crashes and the corresponding error so we can try to reproduce it ? (+ your OS and Python version ?)
I'll look into your problem then :)

(Note: As is, it looks like a strange problem as my native language is French and we have `éèêàçïô` and i never had such problems)

**Comment by danieltellez** [comment] 2018-12-10 11:17
In my case, I did resolve many of these problems using `unidecode`

**Comment by MerlinElMago** [comment] 2018-12-21 20:16
Can post an example please?

**Comment by zigma12** [comment] 2019-04-05 14:56
Hi @C4ptainCrunch,

I am too stuck into what I think to be an encoding issue.

I read online a calendar which is `utf8`-encoded.
`cal = Calendar(urlopen(url).read().decode('utf8'))`

The `description` field of the events contains accents etc.
I can `print` those fields in my terminal without problem.
`for evt in cal.events:`
`....print evt.name.encode('utf8')`
`....print evt.description.encode('utf8')`

The problem is when I try to use something like
`with open(u'my.ics', 'w') as f:`
`....f.writelines(cal)`
or simply `str(cal)`

I attach a MWE (I had to add `.txt` extension to each file because `.py` and `.ics` files are not "supported")
[icsTool.py.txt](https://github.com/C4ptainCrunch/ics.py/files/3048471/icsTool.py.txt)
[testCal.ics.txt](https://github.com/C4ptainCrunch/ics.py/files/3048472/testCal.ics.txt)
[testCal_clean.ics.txt](https://github.com/C4ptainCrunch/ics.py/files/3048473/testCal_clean.ics.txt)


thank you..

**Comment by jvargass** [comment] 2019-06-03 12:38
I have the same issue as @zigma12 
- Python 2.7.15
- MacOs Mojave 10.14

When I try:
`with open('appointment.ics', 'w') as my_file:
my_file.writelines(cal)`

with description with utf-8 caracters, like 'Descripción', for example, the system launch same error **UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 8: ordinal not in range(128)**
Some advances here?

**Comment by C4ptainCrunch** [comment] 2019-06-11 21:16
Hi @zigma12 and @jvargass

ics.py does not support python2 anymore (the language itself won't be supported for long as well : https://pythonclock.org/). Is it possible for you to upgrade to python3 ? If it is, do you still have the error ?

**Comment by zigma12** [comment] 2019-06-12 06:18
Hi @C4ptainCrunch,
thank you for your answer.
I do not have time these days but I'll give it a try and let you know of the result ASAP.

**Comment by C4ptainCrunch** [comment] 2019-08-05 22:52
I'm closing this issue for now. If you have an encoding problem with the latest version of the lib and a modern python3, feel free to reopen :)

**Closed by C4ptainCrunch** 2019-08-05 22:52 UTC
Labels: StackOverflow

**Comment by Blaa00** [comment] 2024-01-30 12:35
I have the same problem with python 3.
I use `ics.Calendar(file.read())` to load the calendar. A capitalized Ä  is converted into \u00c3\u201e when I dump it into a json file and Ã„ in the debugger.
