### ISSUE TITLE
ics does not work with http://chaosradio.ccc.de/chaosradio.ics

### ISSUE THREAD

**Issue by MHohenberg** [C4ptainCrunch/ics.py#108] opened 2017-10-15 09:08 UTC
Traceback (most recent call last):
      File "/usr/local/bin/ical2paleventfile", line 48, in <module>
        c = Calendar(urlopen(url).read().decode('utf-8'))
      File "/home/martin/.local/lib/python2.7/site-packages/ics/icalendar.py", line 71, in __init__
        self._populate(container[0])  # Use first calendar
      File "/home/martin/.local/lib/python2.7/site-packages/ics/component.py", line 52, in _populate
        extractor.function(self, lines)  # Send a list or empty list
      File "/home/martin/.local/lib/python2.7/site-packages/ics/icalendar.py", line 233, in events
        calendar.events = list(map(event_factory, lines))
      File "/home/martin/.local/lib/python2.7/site-packages/ics/icalendar.py", line 232, in <lambda>
        event_factory = lambda x: Event._from_container(x, tz=calendar._timezones)
      File "/home/martin/.local/lib/python2.7/site-packages/ics/component.py", line 31, in _from_container
        k._populate(container)
      File "/home/martin/.local/lib/python2.7/site-packages/ics/component.py", line 55, in _populate
        extractor.function(self, lines[0])  # Send the element
      File "/home/martin/.local/lib/python2.7/site-packages/ics/event.py", line 293, in created
        event.created = iso_to_arrow(line, tz_dict)
      File "/home/martin/.local/lib/python2.7/site-packages/ics/utils.py", line 46, in iso_to_arrow
        naive = arrow.get(val).naive
      File "/home/martin/.local/lib/python2.7/site-packages/arrow/api.py", line 23, in get
        return _factory.get(*args, **kwargs)
      File "/home/martin/.local/lib/python2.7/site-packages/arrow/factory.py", line 142, in get
        dt = parser.DateTimeParser(locale).parse_iso(arg)
      File "/home/martin/.local/lib/python2.7/site-packages/arrow/parser.py", line 95, in parse_iso
        return self._parse_multiformat(string, formats)
      File "/home/martin/.local/lib/python2.7/site-packages/arrow/parser.py", line 209, in _parse_multiformat
        raise ParserError('Could not match input to any of {0}'.format(formats))
    arrow.parser.ParserError: Could not match input to any of ['YYYY-MM-DDTHH:mm']

The file uses a time format without the dashes or the colon:

    DTSTART;TZID=Europe/Berlin:20170928T220000

This appears to be in line with RFC5545.

**Comment by C4ptainCrunch** [comment] 2018-01-29 15:10
Duplicate of #104

**Closed by C4ptainCrunch** 2018-01-29 15:10 UTC
Labels: bug, duplicate
