### ISSUE TITLE
Outputting a Generated Calendar into Calendar is Broken

### ISSUE THREAD

**Issue by eligundry** [C4ptainCrunch/ics.py#87] opened 2016-08-07 05:26 UTC
Hi there, I'm having a bit of trouble piping the output of the `Calendar` back into `Calendar`. Take for example: 

``` python
>>> from ics import Calendar, Event
>>> import arrow
>>> from datetime import timedelta
>>> start = arrow.utcnow()
>>> end = start + timedelta(hours=3)
>>> c = Calendar()
>>> c.events.append(Event(name='Event 1', begin=start, end=end))
>>> c
<Calendar with 1 event>
>>> Calendar(str(c))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/ics/icalendar.py", line 71, in __init__
    self._populate(container[0])  # Use first calendar
  File "/usr/local/lib/python2.7/dist-packages/ics/component.py", line 52, in _populate
    extractor.function(self, lines)  # Send a list or empty list
  File "/usr/local/lib/python2.7/dist-packages/ics/icalendar.py", line 233, in events
    calendar.events = list(map(event_factory, lines))
  File "/usr/local/lib/python2.7/dist-packages/ics/icalendar.py", line 232, in <lambda>
    event_factory = lambda x: Event._from_container(x, tz=calendar._timezones)
  File "/usr/local/lib/python2.7/dist-packages/ics/component.py", line 31, in _from_container
    k._populate(container)
  File "/usr/local/lib/python2.7/dist-packages/ics/component.py", line 55, in _populate
    extractor.function(self, lines[0])  # Send the element
  File "/usr/local/lib/python2.7/dist-packages/ics/event.py", line 293, in created
    event.created = iso_to_arrow(line, tz_dict)
  File "/usr/local/lib/python2.7/dist-packages/ics/utils.py", line 50, in iso_to_arrow
    return arrow.get(val)
  File "/usr/local/lib/python2.7/dist-packages/arrow/api.py", line 23, in get
    return _factory.get(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/arrow/factory.py", line 164, in get
    dt = parser.DateTimeParser(locale).parse_iso(arg)
  File "/usr/local/lib/python2.7/dist-packages/arrow/parser.py", line 112, in parse_iso
    return self._parse_multiformat(string, formats)
  File "/usr/local/lib/python2.7/dist-packages/arrow/parser.py", line 246, in _parse_multiformat
    raise ParserError('Could not match input to any of {0} on \'{1}\''.format(formats, string))
arrow.parser.ParserError: Could not match input to any of [u'YYYY-MM-DDTHH:mm'] on '20160807T052407Z'
```

**Comment by C4ptainCrunch** [comment] 2018-01-29 15:19
I can't reproduce this on python3.6, master and arrow==0.4.2 so i'm closing. Feel free to reopen if you have more context :)

**Closed by C4ptainCrunch** 2018-01-29 15:19 UTC
