### ISSUE TITLE
TypeError: Can't instantiate abstract class EmailAlarm with abstract methods action

### ISSUE THREAD

**Issue by jrsenthilk** [C4ptainCrunch/ics.py#259] opened 2020-09-30 07:50 UTC
I tried the secret iCal url of google and i manage to retrieve the events using the following code:

URL = <google ical URL link>
c = Calendar(requests.get(url).text)

but when I tried it on another google calendar, it reported the following error:

TypeError: Can't instantiate abstract class EmailAlarm with abstract methods action 

Here is the full details:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jrsenthilk/.local/lib/python3.6/site-packages/ics/icalendar.py", line 68, in __init__
    self._populate(containers[0])  # Use first calendar
  File "/home/jrsenthilk/.local/lib/python3.6/site-packages/ics/component.py", line 59, in _populate
    parser(self, lines)  # Send a list or empty list
  File "/home/jrsenthilk/.local/lib/python3.6/site-packages/ics/parsers/icalendar_parser.py", line 71, in parse_vevent
    calendar.events = set(map(event_factory, lines))
  File "/home/jrsenthilk/.local/lib/python3.6/site-packages/ics/parsers/icalendar_parser.py", line 69, in event_factory
    return Event._from_container(x, tz=calendar._timezones)
  File "/home/jrsenthilk/.local/lib/python3.6/site-packages/ics/component.py", line 31, in _from_container
    k._populate(container)
  File "/home/jrsenthilk/.local/lib/python3.6/site-packages/ics/component.py", line 59, in _populate
    parser(self, lines)  # Send a list or empty list
  File "/home/jrsenthilk/.local/lib/python3.6/site-packages/ics/parsers/event_parser.py", line 77, in parse_valarm
    event.alarms = [get_type_from_container(x)._from_container(x) for x in lines]
  File "/home/jrsenthilk/.local/lib/python3.6/site-packages/ics/parsers/event_parser.py", line 77, in <listcomp>
    event.alarms = [get_type_from_container(x)._from_container(x) for x in lines]
  File "/home/jrsenthilk/.local/lib/python3.6/site-packages/ics/alarm/base.py", line 70, in _from_container
    ret = super()._from_container(container, *args, **kwargs)
  File "/home/jrsenthilk/.local/lib/python3.6/site-packages/ics/component.py", line 28, in _from_container
    k = cls()

Any idea on what might be causing this issue? Any help is highly appreciated.

Thanks

**Comment by N-Coder** [comment] 2020-09-30 08:55
This is probably a duplicate of #213, which is fixed in the current stable release v0.7.

**Closed by N-Coder** 2020-09-30 08:55 UTC

**Comment by jrsenthilk** [comment] 2020-09-30 08:58
Thanks for the reply. Let me update and retest.. Thanks again
